// 모든 페이지에서 공통으로 사용할 스타일
export const commonPageStyles = {
  pageContainer: {
    width: '100%',
    minHeight: '100vh',
    paddingTop: '110px',
    paddingBottom: '24px',
    paddingLeft: '16px',
    paddingRight: '16px',
    backgroundColor: '#ffffff',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  contentWrapper: {
    width: '100%',
    maxWidth: '343px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  title: {
    fontSize: '20px',
    fontWeight: '600',
    color: '#333',
    textAlign: 'center',
    position: 'relative',
    marginTop: '-30px',
    marginBottom: '24px',
  },
  card: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: '12px',
    padding: '16px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
    border: '1px solid #e0e0e0',
  },
  button: {
    width: '100%',
    height: '44px',
    borderRadius: '8px',
    border: 'none',
    fontSize: '16px',
    fontWeight: '500',
    cursor: 'pointer',
    backgroundColor: '#00aa9d',
    color: '#fff',
  },
  primaryButton: {
    backgroundColor: '#00aa9d',
    color: '#fff',
  },
  secondaryButton: {
    backgroundColor: '#6c757d',
    color: '#fff',
  },
  input: {
    width: '100%',
    height: '44px',
    padding: '0 12px',
    borderRadius: '8px',
    border: '1px solid #ddd',
    fontSize: '16px',
  },
  textarea: {
    width: '100%',
    minHeight: '100px',
    padding: '12px',
    borderRadius: '8px',
    border: '1px solid #ddd',
    fontSize: '16px',
    resize: 'vertical',
  },
}; 