server:
  port: 8081  # Spring boot Server port
  servlet:
    context-path: /one
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.20.45.80:3306/intern_user1
    username: mdl
    password: mdl
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  web:
    resources:
      static-locations: file:./uploads/

jwt:
  secret: eUD9biuVqLVGtVmebHK7ohjhgYZIO+KxNFACmP7pyC0=


flask:
  server:
    url: http://localhost:5000 # Flask 서버 URL
    

upload:
  perscription:
    dir: uploads/perscriptions/ # 처방전 이미지 저장 경로